title: Annual statistics of Common Crawl robots.txt archives
description: Different annual statistics of the Common Crawl robots.txt archives
latest_crawl: CC-MAIN-2023-50

show_navigation: True
navlist:
  - title: Home
    url: /
  - title: Resources
    url: /tabs/resources

remote_theme: pages-themes/minimal@v0.2.0
plugins:
  - jekyll-remote-theme
