title: Annual statistics of Common Crawl robots.txt archives
description: Different annual statistics of the Common Crawl robots.txt web archives

show_navigation: True
navlist:
  - title: Home
    url: /
  - title: Overview
    url: /overview
  - title: Basic statistics
    url: /basic-statistics
  - title: Top user agents
    url: /top-user-agents
  - title: User agent bias
    url: /user-agent-bias
  - title: Resources
    url: /resources

remote_theme: pages-themes/minimal@v0.2.0
plugins:
  - jekyll-remote-theme
